name : Secret Test
on:
  workflow_dispatch:
    inputs:
     environment: test_environment
jobs:
  Secret-Test:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        submodules: recursive
    - name: Install more dependencies
      run: |
        sudo apt-get install -y \
          make \
          build-essential
    - name: Build
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: make secrettest


